behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 6000
      buffer_size: 28000
      learning_rate: 0.0007
      beta: 0.003
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.5
    keep_checkpoints: 4
    max_steps: 25000000
    time_horizon: 400
    summary_freq: 20000
    self_play:
      save_steps: 40000
      team_change: 140000
      swap_steps: 15000
      window: 15
      play_against_latest_model_ratio: 0.6
      initial_elo: 1200.0
